// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiproje.Entities;

namespace apiproje.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221221085321_mig_creattables")]
    partial class mig_creattables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiproje.Entities.Aksesuar", b =>
                {
                    b.Property<int>("AksesuarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AksesuarAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AksesuarRenk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AksesuarID");

                    b.ToTable("aksesuars");
                });

            modelBuilder.Entity("apiproje.Entities.Kategoriler", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("KategoriID");

                    b.HasIndex("UrunID");

                    b.ToTable("kategorilers");
                });

            modelBuilder.Entity("apiproje.Entities.Urunler", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UrunAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunBeden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunYas")
                        .HasColumnType("int");

                    b.HasKey("UrunID");

                    b.ToTable("urunlers");
                });

            modelBuilder.Entity("apiproje.Entities.Kategoriler", b =>
                {
                    b.HasOne("apiproje.Entities.Urunler", "Urunler")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
